server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: localhost:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: bakainory
    password: megumin123
mybatis-plus:
  type-aliases-package: com.bakainory.springbootdemo.entity.pojo
  mapper-locations:
    - classpath:com/bakainory/springbootdemo/mapper/mapping/*.xml
mybatis:
  mapper-locations:
    - classpath:com/bakainory/springbootdemo/mapper/mapping/*.xml